import React, { useState } from "react";
import Head from "next/head";
import { css } from "@emotion/css";
import GET_DATA from "@/utils/getData";
import { useQuery } from "@apollo/client";
import DetailCard from "@/contianers/DetailCard";

export default function Home() {
  const { loading, error, data } = useQuery(GET_DATA);
  const [name, setName] = useState(""); //CHANGE AT THE END
  const [clicked,setClicked] = useState(false) // CHANGE AT THE END 
  const [countryData,setCountryData] =useState({})

  const clickHandler = ()=>{
    setClicked(true)
    const country= data.countries.find ((country)=> country.name === name);
    setCountryData(country)
  }

  //console.log("useQuery", loading);
  //console.log('data', data.countries)
  return (
    <>
      <Head>
        <title>Country Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={css`
          width: 100vw;
          height: 100vh;
          background-color: #451952;
          color: #e8bcb9;
          display: flex; 
          justify-content: center; 
          align-items: center;
        `}
      >
        {name && clicked ? (
          <DetailCard  data={countryData}/>
        ) : (
          <div
            className={css`
              display: flex;
              flex-direction: column;
              width: 60vw;
              height: 50vh;
              justify-content: center; 
              align-items: center;
            `}
          >
            <p className={css`margin-bottom: 20px;`}>
              If you want to know more about countries, you can search the name{" "}
            </p>
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              className={css`
                width: 50vw;
                margin-top: 20px;
              `}
              placeholder="Enter the name of country "
            />
            <button
              className={css`
                width: 50vw;
                margin-top: 20px;
              `}
              onClick={clickHandler}
            >
              Search
            </button>
          </div>
        )}
      </main>
    </>
  );
}
